import { Injectable, Logger } from '@nestjs/common';
import { REMEDIATION_GUIDES, FALLBACK_GUIDE, IRemediationGuide } from './constants/guides.constants';

@Injectable()
export class RemediationService {
  private readonly logger = new Logger(RemediationService.name);

  /**
   * Identifies the category of vulnerability based on the ruleId and maps it
   * to a pre-defined remediation guide, returning it formatted in Markdown.
   */
  public generateRemediationMarkdown(ruleId: string, severity: string): string {
    const guideKey = this.resolveGuideKey(ruleId);
    const guide: IRemediationGuide = REMEDIATION_GUIDES[guideKey] || FALLBACK_GUIDE;

    this.logger.log(`Generating remediation guide for ruleId: "${ruleId}" using template key: "${guideKey}"`);

    return this.formatMarkdown(guide, ruleId, severity);
  }

  /**
   * Resolves raw ruleId identifiers from tools (e.g., eslint, sonarqube, bandit, trivy)
   * to our catalog's mapped guide keys.
   */
  private resolveGuideKey(ruleId: string): string {
    const normalized = ruleId.toUpperCase().replace(/[^A-Z0-9_]/g, '_');

    if (normalized.includes('SQL') || normalized.includes('INJECTION') || normalized.includes('PARAMET')) {
      return 'SQL_INJECTION';
    }
    if (normalized.includes('SECRET') || normalized.includes('PASSWORD') || normalized.includes('KEY') || normalized.includes('CREDENTIAL')) {
      return 'HARDCODED_SECRETS';
    }
    if (normalized.includes('HEADER') || normalized.includes('HELMET') || normalized.includes('CORS') || normalized.includes('SECURITY_HEADER')) {
      return 'MISSING_SECURITY_HEADERS';
    }
    if (normalized.includes('XSS') || normalized.includes('SCRIPTING') || normalized.includes('SANITIZE') || normalized.includes('ESCAPE')) {
      return 'XSS_VULNERABILITY';
    }

    // Try an exact match on keys
    if (REMEDIATION_GUIDES[normalized]) {
      return normalized;
    }

    return 'FALLBACK';
  }

  /**
   * Format vulnerability details and remediation guide into standard Github Markdown.
   */
  private formatMarkdown(guide: IRemediationGuide, ruleId: string, severity: string): string {
    return `
### [${severity}] Remediation Guide for Rule \`${ruleId}\`
## ${guide.title}

---

#### ⚠️ Engineering Risk Description
${guide.riskDescription}

---

#### 🛑 Insecure Pattern (Vulnerable Implementation)
Below is an example of the pattern triggering this alert:

\`\`\`typescript
${guide.insecurePattern}
\`\`\`

---

#### ✅ Secure Pattern (Remediated Implementation)
Apply the following correction to mitigate this vulnerability:

\`\`\`typescript
${guide.securePattern}
\`\`\`

---
*Generated by the SAST Orchestration Engine Remediation Feedback Service.*
    `.trim();
  }
}
